import { Injectable } from '@angular/core';
import { Menu } from './menu';
import { HttpClient } from '@angular/common/http';

@Injectable({
    providedIn: 'root'
})

export class DataService {

    baseUrl = 'https://crudcrud.com/api/29fdfde92ff6484da9777798c21717d8'; // berbeda untuk setiap mahasiswa

    constructor(private http: HttpClient) {}
  
    getMenus() {
      return this.http.get(`${this.baseUrl}/menu`);
    }
  
    getMenu(id: number) {
      return this.http.get(`${this.baseUrl}/menu/${id}`);
    }
  
    postMenu(menu: Menu) {
      delete menu._id; // we delete the id because it'll generated by server
      return this.http.post(`${this.baseUrl}/menu`, menu);
    }
  
    updateMenu(menu: Menu) {
      const id = menu._id; // we copy the original id 
      delete menu._id; // we delete the original id so the server doesn't reply with error message
      return this.http.put(`${this.baseUrl}/menu/${id}`, null);
    }
  
    deleteMenu(menu: Menu) {
      const id = menu._id; // we copy the original id
      return this.http.delete(`${this.baseUrl}/menu/${id}`);
    }


}
